apps:
  - name     : boggle-dev
    script   : ./src/app.js
    watch    : ./src/server
    instances: 1
    interpreter: babel-node
    exec_mode: fork
    port     : 3000
    env      :
      NODE_ENV: development
  - name     : boggle-prod
    script   : ./web/app.js
    instances: 4
    exec_mode: cluster
    env      :
      NODE_ENV: production
