files:
  include: 'src/styles/**/*.scss'
  ignore: 'src/styles/_mixins.scss'
rules:
  no-important: 0
  property-sort-order: 0
  no-color-literals: 0
  no-css-comments: 0
  no-duplicate-properties: 0
  no-ids: 0
  no-misspelled-properties: 0
  shorthand-values: 0
  clean-import-paths: 0
  class-name-format: 0
  nesting-depth: 0
  no-vendor-prefixes: 0
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
