sudo: required
language: node_js
branches:
  only:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
script:
- yarn -s test:lint
- yarn -s test:jest
- yarn -s test:codecov
deploy:
  provider: script
  skip_cleanup: true
  script: yarn -s lambda:deploy
  on:
    tags: true
