language: node_js
node_js:
- 8.9.0
install:
- npm install # Using npm instead of yarn prevents issue https://github.com/facebook/jest/issues/5772
script:
- npm run -s jest:ci
- npm run -s lint
- npm run -s codecov
