#!/bin/bash
set -e

export NODE_ENV="production"
export DIR=".reports/analyze"
export STATS="${DIR}/stats.json"

mkdir -p ${DIR} &&

yarn -s webpack-cli -p --env.prod --profile --json --config webpack.config.client.js > ${STATS} &&
yarn webpack-bundle-analyzer ${STATS} ./web/public -m static -r ${DIR}/report.html
