#!/usr/bin/env node
const path = require('path');
const fs = require('fs');
const pkg = require('../package.json');

const zip = new require('node-zip')();

zip.file('Dockerfile', `
FROM lquixada/${pkg.name}:${pkg.version}

EXPOSE 3000

CMD ["./node_modules/.bin/pm2", "start", ".process.yml", "--no-daemon"]
`);

const file = path.join(__dirname, '..', 'web', 'build.zip');
const data = zip.generate({base64: false, compression: 'DEFLATE'});

fs.writeFileSync(file, data, 'binary');
