#!/bin/bash
set -e

export NODE_ENV="production"
export APP_NAME="Boggle"
export DIR="./desktop"
export BUILD_DIR="${DIR}/build"

# Build assets
npx babel -D -q src -d $DIR/src &&

cp package*.json $DIR &&

cd $DIR &&

npm install --prod &&

cd .. &&

# Build .app
npx electron-packager $DIR $APP_NAME --overwrite --out=$BUILD_DIR &&

# Build .dmg
npx electron-installer-dmg $BUILD_DIR/$APP_NAME-darwin-x64/$APP_NAME.app --out=$BUILD_DIR/$APP_NAME-darwin-x64 $APP_NAME
