#!/bin/bash
set -e

export NODE_ENV="benchmark"
export DIR=".reports/flame"

mkdir -p ${DIR} &&

npm run -s web:build &&
npx clinic flame \
  -D "${DIR}/{pid}" \
  -F "${DIR}/{pid}/index.html" \
  --on-port 'autocannon http://localhost:3000/' \
  -- node web/app.js
